[package]
name = "hello-world"
version = "0.1.0"
edition = "2018"
authors = ["Lucas Guimar√£es <lucaslgr1206@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
